In [1]:
import classifiers as clf

import pickle

import pandas as pd
import numpy  as np

from sklearn.model_selection import train_test_split
from imblearn.over_sampling  import SMOTE
from imblearn.over_sampling  import SMOTENC

import matplotlib.pyplot as plt
import seaborn           as sns
sns.set_style("darkgrid")

import warnings
warnings.filterwarnings('ignore')

In [72]:
y = np.array([['E'],['E'],['N'],['N'],['N'],['N'],['E'],['N'],['E'],['N'],['N'],['N']])
X = np.array([[1,0,1,0],[0,0,0,0],[0,1,0,1],[1,0,0,1],[0,1,1,0],[0,1,1,1],[1,1,1,1],[0,0,0,1],[1,0,0,0],[1,1,1,1],[0,0,0,1],[1,0,0,0]])

In [63]:
X = X.astype(float)

In [73]:
X.shape

(12, 4)

In [74]:
X

array([[1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0]])

In [75]:
y

array([['E'],
       ['E'],
       ['N'],
       ['N'],
       ['N'],
       ['N'],
       ['E'],
       ['N'],
       ['E'],
       ['N'],
       ['N'],
       ['N']], dtype='<U1')

In [76]:
y.shape

(12, 1)

In [81]:
sample_ratio = {'N': 8, 'E': 8}
smote = SMOTE(k_neighbors=2)
smote

SMOTE(k_neighbors=2, kind='deprecated', m_neighbors='deprecated', n_jobs=1,
   out_step='deprecated', random_state=None, ratio=None,
   sampling_strategy='auto', svm_estimator='deprecated')

In [82]:
X_train_smote, y_train_smote = smote.fit_sample(X, y)

In [83]:
X

array([[1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0]])

In [84]:
X_train_smote

array([[1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 1, 0]])

In [85]:
y_train_smote

array(['E', 'E', 'N', 'N', 'N', 'N', 'E', 'N', 'E', 'N', 'N', 'N', 'E',
       'E', 'E', 'E'], dtype='<U1')

In [86]:
X_train_smote.shape

(16, 4)

In [87]:
y_train_smote.shape

(16,)